apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: optimizer-role-cluster
rules:
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: [apiextensions.k8s.io]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: [apps]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: ["flink.apache.org"]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: ["chaos-mesh.org"]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "list", "get", "watch"]
  - apiGroups: ["autoscaling"]
    resources: ["horizontalpodautoscalers"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: default-optimizer-rolebinding-cluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: optimizer-role-cluster
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demeter-optimizer
  namespace: default
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: demeter-optimizer
  template:
    metadata:
      labels:
        app: demeter-optimizer
    spec:
      containers:
        - name: demeter-optimizer
          image: mcd01/demeter_optimizer:latest
          imagePullPolicy: Always
